### PR TITLE
The website was refactored for Accessibility

### PR DESCRIPTION
**Pull request by kkolade**
- Page Title: No issues were found
- Image Text Alternatives: All dummy text for the work section was removed
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L93
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L122
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L151
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L180
- Text headings: Adjusted to reflect a hierarchy
  - All h1 except the Hero section changed to h2
  https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L211
 https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L300
  - All heading in cards changed to h3
  https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L97
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L126
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L155
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L184
- Color Contrast: The following elements were adjusted to improve the color contrast
   - Let's connect CTA
   https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L58
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/css/style.css#L288-L292
   - Card buttons 
 https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L109-L115  
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L138-L144
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L167-L173
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L196-L202
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/css/style.css#L153-L167
   - Text-Area - The Contrast of the placeholder was adjusted for accessibility
   https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/index.html#L332
https://github.com/kkolade/kolakolade.me/blob/1888deb7b5064c9208bb808937452212e1f37476/css/style.css#L272-L279
- Resize : No accessibility error was found
- Interaction: No accessibility error was found
- Moving content: No accessibility error was found
- Multi-media : No accessibility error was found
- Page Structure: No accessibility error was found

### CODE REVIEW

**Review by Tadesse-Alemayehu — COMMENTED** [review]
### Hi @kkolade 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

Dear @kkolade, this is a pair programming exercise, we need to see both of you collaborating on the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kkolade** [comment]
Hi @Tadesse-Alemayehu Thanks for the feedback really appreciated and we will make the suggested changes accordingly
- The alt text for the images was removed because of suggestions in the study material
Screen Shot 2022-11-08 at 19 48 19
- The submission has contributions from both partners, and the third commit in the branch is from my partner, also the submission instruction asked that only 1 submission be made on the behalf of the group

Screen Shot 2022-11-08 at 19 53 43

Please further feedback and comment will be appreciated before further submission

**Comment by Tadesse-Alemayehu** [comment]
- Dear @kkolade, the projects should be completed through collaboration and commits from both partners. then one of you can submit it. I only see your commit's in this pull request. This is to make sure you both have worked on the project.

**Comment by Tadesse-Alemayehu** [comment]
- About the images. I was looking at your project and the `project` image is not decorative images, those images have meanings about the project. hence better to give them alternative texts. but again this is a suggestion, You will get a review once you submit a project for review.

**Comment by kkolade** [comment]
@Tadesse-Alemayehu the suggested reviews have been implemented
- Alt texts were added to images

**Review by mgmediaweb — APPROVED** [review]
Hi @kkolade , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

approved1

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
